version: '3.8'

services:
  # 1. Database MySQL
  mysql-db:
    image: mysql:8.0
    container_name: bizflow-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Mật khẩu root
      MYSQL_DATABASE: bizflow_db # Tên DB sẽ tự tạo
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # 2. Redis Cache (Để sau này dùng, giờ cứ cài sẵn cho oách)
  redis-cache:
    image: redis:alpine
    container_name: bizflow-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data: