name: mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 1. Quản lý trạng thái & UI
  provider: ^6.1.1
  google_fonts: ^6.1.0

  # 2. Gọi API & Xử lý dữ liệu
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  dio: ^5.4.0
  go_router: ^13.0.0
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.1

  # 3. Tiện ích
  font_awesome_flutter: ^10.7.0
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png